# Generated by Django 2.1.2 on 2018-10-30 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 16', regex='^[0-9]{16}$')]),
        ),
    ]
