# Generated by Django 2.1.2 on 2018-10-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_auto_20181030_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pincode',
            field=models.CharField(default=None, editable=False, max_length=100),
        ),
    ]
