# Generated by Django 2.1.2 on 2018-10-31 14:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_auto_20181030_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='card_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='card_to', to='banking.Card'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sum',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
