# Generated by Django 2.1.2 on 2018-10-31 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_auto_20181031_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='card_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='card_to', to='banking.Card'),
        ),
    ]
