# Generated by Django 2.1.2 on 2018-10-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_transaction_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='operation',
            field=models.CharField(choices=[('plus', 'Put money'), ('minus', 'Take money'), ('transfer', 'Transfer money')], default='plus', max_length=16),
        ),
    ]
